title: Johnny-Zhuang's Technology Blog
description: My Personal Technology Blog
author: Johnny-Zhuang
github: https://github.com/iamjohnnyzhuang
about: LOVE CODE,LOVE LIFE,LOVE DAWN.
disqus_shortname: iamjohnnyzhuang
google_analytics: UA-80316544-1

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-weibo
      link: "http://weibo.com/1936027247/profile?topnav=1&wvr=6"
    # - icon: fa-skype
      # link: "#"
    # - icon: fa-twitter
      # link: "https://twitter.com/agusmakmun6"
    - icon: fa-linkedin
      link: "http://www.linkedin.com/?trk=nav_lingying_logo"
    # - icon: fa-stack-exchange
      # link: "#"

# share:
  # twitter_username: agusmakmun6
  # fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Github
      url: https://github.com/iamjohnnyzhuang
    - text: XML Feed
      url: /feed.xml

url: "https://iamjohnnyzhuang.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
highlighter: pygments
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

#阅读处理
safe: false
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# 内容过滤
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# 转换
lsi:         false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart


